### PR TITLE
suggest a journal and start paper/

### PR DESCRIPTION
**Pull request by bueler**
I'm starting paper/ in this branch with a suggested journal, namely Optimization Methods and Software.  I have not published there but I think is a respected journal with a practical bent.  The editor is a VI guy I have met briefly, namely Stefan Ulbrich.

I also suggest a title: "Free-boundary oriented adaptive mesh refinement for obstacle problems" [edited].  The first three words flag the method as not just the DWR idea.  The formal property I mentioned, where these AMR methods are no ops if either the whole domain is active or the whole domain is inactive, should feature prominently in the intro.  The heuristic nature of the algorithms will be accepted more, I think, with this flagging.

Note that you don't need to pull right away ... up to you.

Comments on little files:  See `.gitignore`.  Generally there is no reason to push the binaries (.pdf) or temp files (.log, .aux, ...) generated during pdflatex action, so they are ignored.  Also see `makefile`; now `make` generates `viamr.pdf`, and `make clean` removes the clutter.

Final idea:  I think building this additively (choose what you want from ThesisWork and move it) is better than subtractive (start from your whole project and trim).  In particular, I think we should hold off on putting results into the paper, but definitely think about what they should be and generate them and discuss.  But I can (additively, taking from ThesisWork) help to work on the text of the abstract, Intro, Methods, Discussion, Conclusion kind of text right away.

What do you think?

### CODE REVIEW

**Comment by bueler** [comment]
See [the about page for the Opt Meth Soft journal](https://www.tandfonline.com/journals/goms20/about-this-journal#aims-and-scope) for why I think it is reasonable.  Alternatives I am aware of include SIAM J Control Opt and SIAM J Sci Comput.  For the former, I am not sure how much they expect a novel proof.  We can at least offer open tested software.

**Comment by bueler** [comment]
One more comment regarding journal choice:  I think Opt Meths Software is well-aligned content wise, but it is a commerical journal.  Practically I suppose this is not a big problem; we should post a just-before-submission version as an arxiv preprint and thus the world can read for free (ignoring the further scihub route).  On the other hand I like society journals, e.g. SIAM or ESAIM cause they are not evil.  Let me know thoughts as much as you want.

**Comment by bueler** [comment]
Another thought:  You can decide on your professional name; I just guessed.  Long ago I decided to make mine short: "Edward L Bueler" to "Ed Bueler".

**Review by StefanoFochesatto — COMMENTED** [review]
Looks good!

**Pull request merged**
